version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-containerize-a-laravel-application-for-development-with-docker-compose-on-ubuntu-18-04-ru
services:
  app:
    build:
      context: ./docker
      args:
        XDEBUG: '${XDEBUG:-on}'
    image: '${APP_NAME}-app'
    restart: unless-stopped
    container_name: '${APP_NAME}-app'
    volumes:
      - './:/var/www'
      - './storage/logs/php:/var/log/php'
      - './docker/configs/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - docker-compose.env
    networks:
      - study-network

  #Nginx Service https://hub.docker.com/_/nginx
  nginx:
    image: nginx:latest
    container_name: '${APP_NAME}-nginx'
    restart: unless-stopped
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_PORT_SSL:-443}:443'
    volumes:
      - './:/var/www'
      - './storage/logs/nginx:/var/log/nginx'
      - './docker/configs/nginx/conf.d/:/etc/nginx/conf.d/'
    networks:
      - study-network

  #MySQL Service https://hub.docker.com/_/mysql
  db:
    image: mysql:8.0.12
    container_name: '${APP_NAME}-db'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    volumes:
      - 'study:/var/lib/mysql'
      - './storage/logs/mysql:/var/log/mysql:rw'
      - './docker/configs/mysql/conf.d:/etc/mysql/conf.d'
    networks:
      - study-network

  adminer:
    image: adminer
    container_name: '${APP_NAME}-adminer'
    restart: always
    ports:
      - '${ADMINER_PORT:-8080}:8080'
    networks:
      - study-network

#Docker Networks
networks:
  study-network:
    driver: bridge

#Volumes
volumes:
  study:
    driver: local
