#!/bin/sh

##to make sum link run git-hook-install
dockerRun() {
    docker-compose exec -T main "$@"
}

error() {
  printf "\033[0;31m %s \033[0m\n" "$1"
}

echo "Running pre push hook.. in developing..."


exit $?
